local ts_comments = require("ts-comments")

local config = {
  commentstring = true,
  lang = {
    astro = "<!-- %s -->",
    html = "<!-- %s -->",
    svelte = "<!-- %s -->",
    vue = "<!-- %s -->",
    xaml = "<!-- %s -->",
    css = "/* %s */",
    scss = "/* %s */",
    styled = "/* %s */",
    javascript = {
      "// %s",
      "/* %s */",
      call_expression = "// %s",
      jsx_attribute = "// %s",
      jsx_element = "{/* %s */}",
      jsx_fragment = "{/* %s */}",
      spread_element = "// %s",
      statement_block = "// %s",
    },
    tsx = {
      "// %s",
      "/* %s */",
      call_expression = "// %s",
      jsx_attribute = "// %s",
      jsx_element = "{/* %s */}",
      jsx_fragment = "{/* %s */}",
      spread_element = "// %s",
      statement_block = "// %s",
    },
    typescript = { "// %s", "/* %s */" },
    c = "// %s",
    cpp = "// %s",
    go = "// %s",
    rust = { "// %s", "/* %s */" },
    python = "# %s",
    bash = "# %s",
    sh = "# %s",
    zsh = "# %s",
    yaml = "# %s",
    toml = "# %s",
    json = "// %s",
    jsonc = "// %s",
    sql = "-- %s",
    markdown = "<!-- %s -->",
    graphql = "# %s",
    handlebars = "{{! %s }}",
    glimmer = "{{! %s }}",
    twig = "{# %s #}",
    php = "// %s",
  },
}
ts_comments.setup(config)
