-- nvim --clean --headless -i NONE -l tests/nvim.lua
local root = vim.fs.dirname(vim.fs.dirname(vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":p")))
vim.opt.rtp:prepend(root)
vim.o.swapfile = false
local api = vim.api
local plugin = require("tab_buffers")
local tests, notices = {}, {}
local sequence = 0
local real_notify = vim.notify
vim.notify = function(message)
  notices[#notices + 1] = message
end
local saved = {
  nvim_win_set_buf = api.nvim_win_set_buf,
  nvim_buf_delete = api.nvim_buf_delete,
  nvim_open_win = api.nvim_open_win,
}

local function equal(actual, expected)
  assert(vim.deep_equal(actual, expected), "expected " .. vim.inspect(expected) .. ", got " .. vim.inspect(actual))
end

local function raises(fn, text)
  local ok, err = pcall(fn)
  assert(not ok, "expected an error")
  if text then
    assert(tostring(err):find(text, 1, true), tostring(err))
  end
end

local function drain()
  for _ = 1, 2 do
    local ready = false
    vim.schedule(function()
      ready = true
    end)
    assert(
      vim.wait(1000, function()
        return ready
      end, 1),
      "scheduled work did not finish"
    )
  end
end

local function file(name, lines)
  sequence = sequence + 1
  local buf = api.nvim_create_buf(true, false)
  api.nvim_buf_set_name(buf, "/private/tmp/tab-buffers-tests/" .. sequence .. "/" .. (name or "file.lua"))
  api.nvim_buf_set_lines(buf, 0, -1, false, lines or { "text" })
  vim.bo[buf].modified = false
  return buf
end

local function show(buf)
  api.nvim_set_current_buf(buf)
  drain()
end

local function reset()
  for name, fn in pairs(saved) do
    api[name] = fn
  end
  plugin.teardown()
  api.nvim_create_augroup("TabBuffersTests", { clear = true })
  vim.o.hidden, vim.o.confirm, vim.o.autowrite = true, false, false
  for _, buf in ipairs(api.nvim_list_bufs()) do
    if api.nvim_buf_is_valid(buf) then
      vim.bo[buf].modified = false
      vim.bo[buf].bufhidden = ""
    end
  end
  for _, win in ipairs(api.nvim_list_wins()) do
    if api.nvim_win_get_config(win).relative ~= "" then
      api.nvim_win_close(win, true)
    end
  end
  vim.cmd("silent! tabonly!")
  vim.cmd("silent! only!")
  vim.wo.previewwindow = false
  vim.cmd("enew!")
  vim.t.tab_buffers_excluded = nil
  local current = api.nvim_get_current_buf()
  for _, buf in ipairs(api.nvim_list_bufs()) do
    if buf ~= current then
      api.nvim_buf_delete(buf, { force = true })
    end
  end
  notices = {}
  drain()
end

local function test(name, fn)
  tests[#tests + 1] = { name = name, run = fn }
end

test("working functions require setup; teardown is idempotent", function()
  raises(function()
    plugin.buffers()
  end, "setup")
  raises(function()
    plugin.refresh()
  end, "setup")
  raises(function()
    plugin.next()
  end, "setup")
  equal(plugin.teardown(), false)
  equal(plugin.setup(), true)
  equal(plugin.teardown(), true)
  equal(plugin.teardown(), false)
end)

test("bootstrap distributes visible buffers and appends hidden buffers to the current tab", function()
  local hidden, visible, other = file(), file(), file()
  show(hidden)
  show(visible)
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  show(other)
  local second = api.nvim_get_current_tabpage()
  plugin.setup()
  equal(plugin.buffers(first), { visible })
  equal(plugin.buffers(second), { other, hidden })
  equal(plugin.owners(hidden), { second })
  equal(plugin.contains(other), true)
  equal(plugin.tabs(), { first, second })
end)

test("background buffers remain unowned until shown or explicitly added", function()
  plugin.setup()
  local first, second = file(), file()
  drain()
  equal(plugin.owners(first), {})
  equal(plugin.add(second), true)
  show(first)
  equal(plugin.buffers(), { second, first })
  show(second)
  equal(plugin.buffers(), { second, first })
end)

test("unnamed buffers enroll after text and remain owned after clearing", function()
  plugin.setup()
  local buf = api.nvim_get_current_buf()
  equal(plugin.buffers(), {})
  api.nvim_buf_set_lines(buf, 0, -1, false, { "draft" })
  api.nvim_exec_autocmds("TextChanged", { buffer = buf })
  drain()
  equal(plugin.buffers(), { buf })
  api.nvim_buf_set_lines(buf, 0, -1, false, { "" })
  vim.bo[buf].modified = false
  plugin.refresh()
  equal(plugin.buffers(), { buf })
end)

test("special, floating and preview windows do not enroll buffers", function()
  local main = file()
  show(main)
  local floating, preview = file(), file()
  local float = api.nvim_open_win(floating, false, { relative = "editor", width = 10, height = 2, row = 1, col = 1 })
  vim.cmd("vsplit")
  local preview_win = api.nvim_get_current_win()
  vim.wo[preview_win].previewwindow = true
  api.nvim_win_set_buf(preview_win, preview)
  plugin.setup()
  equal(plugin.buffers(), { main })
  equal(plugin.owners(preview), {})
  equal(plugin.owners(floating), {})
  vim.wo[preview_win].previewwindow = false
  local tree = api.nvim_create_buf(true, false)
  vim.bo[tree].buftype = "nofile"
  api.nvim_win_set_buf(preview_win, tree)
  plugin.refresh()
  equal(plugin.owners(tree), {})
  equal(plugin.next(), nil)
  equal(plugin.move(1), false)
  equal(plugin.add(), false)
  equal(api.nvim_win_get_buf(preview_win), tree)
  equal(api.nvim_win_get_buf(float), floating)
end)

test("repeated setup preserves order and does not duplicate autocmds", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  show(b)
  plugin.move_to(1)
  local count = #api.nvim_get_autocmds({ event = "TabClosedPre" })
  plugin.setup()
  equal(plugin.buffers(), { b, a })
  equal(#api.nvim_get_autocmds({ event = "TabClosedPre" }), count)
end)

test("teardown cancels queued work without changing real buffers", function()
  plugin.setup()
  local buf = file()
  api.nvim_set_current_buf(buf)
  local events = 0
  api.nvim_create_autocmd("User", {
    group = "TabBuffersTests",
    pattern = "TabBuffersChanged",
    callback = function()
      events = events + 1
    end,
  })
  plugin.teardown()
  drain()
  equal(events, 0)
  equal(api.nvim_buf_is_valid(buf), true)
  equal(api.nvim_get_current_buf(), buf)
  plugin.setup()
  equal(plugin.buffers(), { buf })
end)

test("rename of a hidden shared buffer preserves owners and position", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  show(b)
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  local second = api.nvim_get_current_tabpage()
  plugin.add(a)
  api.nvim_buf_set_name(a, api.nvim_buf_get_name(a) .. ".renamed")
  drain()
  equal(plugin.buffers(first), { a, b })
  equal(plugin.buffers(second), { a })
  equal(plugin.owners(a), { first, second })
end)

test("unlisting and wiping remove membership after events finish", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  show(b)
  vim.bo[a].buflisted = false
  drain()
  equal(plugin.buffers(), { b })
  equal(api.nvim_buf_is_valid(a), true)
  vim.cmd("bwipeout " .. b)
  drain()
  equal(plugin.owners(b), {})
  equal(plugin.buffers(), {})
end)

test("tab split shares a buffer; tabmove preserves ownership and independent order", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  show(b)
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tab split")
  drain()
  local second = api.nvim_get_current_tabpage()
  equal(plugin.buffers(second), { b })
  plugin.add(a)
  equal(plugin.buffers(second), { b, a })
  equal(plugin.buffers(first), { a, b })
  vim.cmd("tabmove 0")
  drain()
  equal(plugin.tabs(), { second, first })
  equal(plugin.owners(b), { first, second })
end)

test("order functions and metadata sorts are one-time and tab-local", function()
  plugin.setup()
  local z, a, m = file("z.lua"), file("a.lua"), file("m.lua")
  show(z)
  show(a)
  show(m)
  equal(plugin.move(-1), true)
  equal(plugin.buffers(), { z, m, a })
  equal(plugin.move_to(1), true)
  equal(plugin.buffers(), { m, z, a })
  equal(plugin.sort("name"), true)
  equal(plugin.buffers(), { a, m, z })
  equal(plugin.sort("path"), true)
  equal(plugin.buffers(), { z, a, m })
  equal(plugin.sort("id"), false)
  equal(plugin.reorder({ m, a, z }), true)
  equal(
    plugin.sort(function(x, y)
      return x < y
    end),
    true
  )
  local new = file("0.lua")
  plugin.add(new)
  equal(plugin.buffers(), { z, a, m, new })
  local before = plugin.buffers()
  raises(function()
    plugin.sort(function()
      error("bad comparator")
    end)
  end, "bad comparator")
  equal(plugin.buffers(), before)
end)

test("navigation follows model order and restores bufhidden with hidden disabled", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  show(b)
  plugin.reorder({ b, a })
  vim.bo[b].modified = true
  vim.bo[b].bufhidden = "wipe"
  vim.o.hidden = false
  equal(plugin.next(), a)
  equal(api.nvim_buf_is_valid(b), true)
  equal(vim.bo[b].modified, true)
  equal(vim.bo[b].bufhidden, "wipe")
  equal(vim.o.hidden, false)
  equal(vim.bo[b].buflisted, true)
  equal(plugin.next({ wrap = false }), nil)
  equal(plugin.previous(), b)
  equal(plugin.switch(2), b)
end)

test("changes coalesce; no-op operations do not emit change events", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  show(b)
  local events = {}
  api.nvim_create_autocmd("User", {
    group = "TabBuffersTests",
    pattern = "TabBuffersChanged",
    callback = function(args)
      events[#events + 1] = args.data.tabs
    end,
  })
  plugin.move_to(1)
  plugin.move_to(2)
  drain()
  equal(events, { { api.nvim_get_current_tabpage() } })
  events = {}
  plugin.move(0)
  plugin.add(b)
  plugin.refresh()
  drain()
  equal(events, {})
end)

test("stale handles and invalid arguments have no side effects", function()
  plugin.setup()
  local a = file()
  show(a)
  equal({ plugin.add(999999) }, { false, "invalid buffer handle" })
  equal({ plugin.move(1, { tab = 999999 }) }, { false, "invalid tab handle" })
  equal({ plugin.next({ win = 999999 }) }, { [2] = "invalid window handle for this tab" })
  raises(function()
    plugin.move(1.5)
  end)
  raises(function()
    plugin.add(a, { tab = 0 })
  end)
  raises(function()
    plugin.next({ wrap = 1 })
  end)
  raises(function()
    plugin.sort("unknown")
  end)
  raises(function()
    plugin.reorder({})
  end)
  equal(plugin.buffers(), { a })
end)

test("shared modified close replaces all owner splits without deleting text", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  show(b)
  show(a)
  local first = api.nvim_get_current_tabpage()
  vim.cmd("vsplit")
  local windows = api.nvim_tabpage_list_wins(first)
  vim.cmd("tabnew")
  local second = api.nvim_get_current_tabpage()
  plugin.add(a)
  api.nvim_set_current_tabpage(first)
  drain()
  local focus = api.nvim_get_current_win()
  vim.bo[a].modified, vim.bo[a].bufhidden = true, "wipe"
  vim.o.hidden = false
  local report = plugin.close()
  equal(report, { closed = { a }, failed = {}, tab_closed = false })
  equal(api.nvim_tabpage_list_wins(first), windows)
  for _, win in ipairs(windows) do
    equal(api.nvim_win_get_buf(win), b)
  end
  equal(api.nvim_get_current_win(), focus)
  equal(plugin.owners(a), { second })
  equal(vim.bo[a].modified, true)
  equal(vim.bo[a].bufhidden, "wipe")
  equal(vim.bo[a].buflisted, true)
  equal(vim.o.hidden, false)
end)

test("exclusive close preserves split layout and uses the right replacement", function()
  plugin.setup()
  local a, b, c = file(), file(), file()
  show(a)
  show(b)
  show(c)
  show(b)
  vim.cmd("vsplit")
  local windows, layout = api.nvim_list_wins(), vim.fn.winlayout()
  equal(plugin.close(), { closed = { b }, failed = {}, tab_closed = false })
  equal(api.nvim_list_wins(), windows)
  equal(vim.fn.winlayout(), layout)
  for _, win in ipairs(windows) do
    equal(api.nvim_win_get_buf(win), c)
  end
  equal(api.nvim_buf_is_valid(b), false)
  equal(plugin.buffers(), { a, c })
end)

test("modified exclusive close refuses without changing windows or membership", function()
  plugin.setup()
  local a = file()
  show(a)
  vim.bo[a].modified = true
  local report = plugin.close()
  equal(report.closed, {})
  equal(report.failed, { { buf = a, message = "unsaved changes" } })
  equal(api.nvim_get_current_buf(), a)
  equal(plugin.buffers(), { a })
  equal(#notices, 1)
end)

test("close_others partially succeeds and preserves modified exclusive targets", function()
  plugin.setup()
  local a, b, c, d = file(), file(), file(), file()
  show(a)
  show(b)
  show(c)
  show(d)
  show(a)
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  local second = api.nvim_get_current_tabpage()
  plugin.add(d)
  api.nvim_set_current_tabpage(first)
  drain()
  vim.bo[b].modified, vim.bo[d].modified = true, true
  local report = plugin.close_others()
  equal(report.closed, { c, d })
  equal(report.failed, { { buf = b, message = "unsaved changes" } })
  equal(plugin.buffers(first), { a, b })
  equal(plugin.owners(d), { second })
  equal(api.nvim_buf_is_valid(c), false)
  equal(api.nvim_get_current_buf(), a)
  equal(#notices, 1)
end)

test("left, right and all closure follow tab order; the last tab keeps a blank buffer", function()
  plugin.setup()
  local a, b, c, d = file(), file(), file(), file()
  show(a)
  show(b)
  show(c)
  show(d)
  show(c)
  equal(plugin.close_left().closed, { a, b })
  equal(plugin.buffers(), { c, d })
  equal(plugin.close_right().closed, { d })
  equal(plugin.close_all(), { closed = { c }, failed = {}, tab_closed = false })
  equal(#api.nvim_list_tabpages(), 1)
  equal(plugin.buffers(), {})
  equal(api.nvim_buf_get_name(0), "")
  equal(api.nvim_buf_get_lines(0, 0, -1, false), { "" })
end)

test("closing a noncurrent buffer/tab preserves focus and uses explicit handles", function()
  plugin.setup()
  local a, b, c = file(), file(), file()
  show(a)
  show(b)
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  show(c)
  local second, focus = api.nvim_get_current_tabpage(), api.nvim_get_current_win()
  equal(plugin.close({ tab = first, buf = b }).closed, { b })
  equal(api.nvim_get_current_tabpage(), second)
  equal(api.nvim_get_current_win(), focus)
  local report = plugin.close({ tab = first, buf = a })
  equal(report, { closed = { a }, failed = {}, tab_closed = true })
  equal(api.nvim_tabpage_is_valid(first), false)
  equal(api.nvim_get_current_win(), focus)
end)

test("empty selections and implicit special-window close functions are no-ops", function()
  plugin.setup()
  local a = file()
  show(a)
  vim.cmd("vsplit")
  local tree = api.nvim_create_buf(true, false)
  vim.bo[tree].buftype = "nofile"
  show(tree)
  for _, fn in ipairs({
    plugin.close,
    plugin.close_all,
    plugin.close_others,
    plugin.close_left,
    plugin.close_right,
    plugin.close_tab,
  }) do
    equal(fn(), { closed = {}, failed = {}, tab_closed = false })
  end
  equal(plugin.buffers(), { a })
  equal(api.nvim_get_current_buf(), tree)
  equal(plugin.close_others({ buf = tree }).closed, {})
end)

test("force closes an exclusive modified buffer but never deletes a shared one", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  show(b)
  vim.bo[b].modified = true
  equal(plugin.close({ force = true }).closed, { b })
  equal(api.nvim_buf_is_valid(b), false)
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  plugin.add(a)
  api.nvim_set_current_tabpage(first)
  drain()
  vim.bo[a].modified = true
  equal(plugin.close({ force = true }).tab_closed, true)
  equal(api.nvim_buf_is_valid(a), true)
  equal(vim.bo[a].modified, true)
end)

test("window-update failures roll back all original splits and membership", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  show(b)
  vim.cmd("vsplit")
  local windows = api.nvim_list_wins()
  local calls = 0
  api.nvim_win_set_buf = function(win, buf)
    calls = calls + 1
    if calls == 2 then
      error("injected window failure")
    end
    return saved.nvim_win_set_buf(win, buf)
  end
  local report = plugin.close()
  equal(report.closed, {})
  equal(#report.failed, 1)
  assert(report.failed[1].message:find("injected window failure", 1, true))
  for _, win in ipairs(windows) do
    equal(api.nvim_win_get_buf(win), b)
  end
  equal(plugin.buffers(), { a, b })
end)

test("deletion failures restore windows, text and destructive bufhidden options", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  show(b)
  vim.bo[b].bufhidden = "delete"
  api.nvim_buf_delete = function(buf, opts)
    if buf == b then
      error("injected deletion failure")
    end
    return saved.nvim_buf_delete(buf, opts)
  end
  local report = plugin.close()
  equal(report.closed, {})
  equal(#report.failed, 1)
  equal(api.nvim_get_current_buf(), b)
  equal(vim.bo[b].bufhidden, "delete")
  equal(plugin.buffers(), { a, b })
  equal(api.nvim_buf_get_lines(b, 0, -1, false), { "text" })
end)

test("exclusive buffers displayed in floating previews are preserved", function()
  plugin.setup()
  local a = file()
  show(a)
  api.nvim_open_win(a, false, { relative = "editor", width = 10, height = 2, row = 1, col = 1 })
  local report = plugin.close({ force = true })
  equal(report.closed, {})
  equal(#report.failed, 1)
  equal(plugin.buffers(), { a })
  equal(api.nvim_buf_is_valid(a), true)
end)

test("transfer replaces source windows and preserves an existing destination position", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  show(b)
  show(a)
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  local second = api.nvim_get_current_tabpage()
  plugin.add(b)
  plugin.add(a)
  api.nvim_set_current_tabpage(first)
  drain()
  vim.bo[a].modified, vim.bo[a].bufhidden = true, "wipe"
  vim.o.hidden = false
  equal(plugin.transfer(second, { index = 1 }), true)
  equal(plugin.buffers(first), { b })
  equal(plugin.buffers(second), { b, a })
  equal(api.nvim_get_current_buf(), b)
  equal(vim.bo[a].modified, true)
  equal(vim.bo[a].bufhidden, "wipe")
end)

test("transferring the last buffer closes its source tab without deleting it", function()
  plugin.setup()
  local a = file()
  show(a)
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  local second = api.nvim_get_current_tabpage()
  api.nvim_set_current_tabpage(first)
  drain()
  vim.bo[a].modified = true
  equal(plugin.transfer(second), true)
  equal(api.nvim_tabpage_is_valid(first), false)
  equal(plugin.owners(a), { second })
  equal(api.nvim_buf_is_valid(a), true)
end)

test("close_tab preflight is atomic; force deletes only exclusive buffers", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  show(b)
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  local second = api.nvim_get_current_tabpage()
  plugin.add(a)
  vim.bo[a].modified, vim.bo[b].modified = true, true
  local report = plugin.close_tab({ tab = first })
  equal(report.tab_closed, false)
  equal(report.closed, {})
  equal(report.failed, { { buf = b, message = "unsaved changes" } })
  equal(plugin.buffers(first), { a, b })
  equal(api.nvim_tabpage_is_valid(first), true)
  report = plugin.close_tab({ tab = first, force = true })
  equal(report.tab_closed, true)
  equal(report.closed, { a, b })
  equal(api.nvim_buf_is_valid(b), false)
  equal(plugin.owners(a), { second })
  equal(vim.bo[a].modified, true)
end)

test("close_tab refuses the final tab without exiting or removing its buffers", function()
  plugin.setup()
  local a = file()
  show(a)
  local report = plugin.close_tab({ force = true })
  equal(report.error, "cannot close the last tab")
  equal(report.closed, {})
  equal(api.nvim_get_current_buf(), a)
end)

test("external inactive tab close deletes exclusive buffers and keeps shared buffers", function()
  plugin.setup()
  local a, b, c = file(), file(), file()
  show(a)
  show(b)
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  show(c)
  local second = api.nvim_get_current_tabpage()
  plugin.add(a)
  vim.cmd("tabclose " .. api.nvim_tabpage_get_number(first))
  drain()
  equal(api.nvim_buf_is_valid(b), false)
  equal(plugin.owners(a), { second })
  equal(plugin.buffers(), { c, a })
  equal(#notices, 0)
end)

test("external closure preserves modified buffers even with bufhidden wipe and tabclose!", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  show(b)
  local second = api.nvim_get_current_tabpage()
  api.nvim_set_current_tabpage(first)
  vim.bo[a].modified, vim.bo[a].bufhidden = true, "wipe"
  vim.cmd("tabclose!")
  drain()
  equal(api.nvim_buf_is_valid(a), true)
  equal(vim.bo[a].modified, true)
  equal(vim.bo[a].bufhidden, "wipe")
  equal(plugin.owners(a), { second })
  equal(#notices, 1)
end)

test("tabonly removes all closed owners before deleting or recovering buffers", function()
  plugin.setup()
  local a, b, c = file(), file(), file()
  show(a)
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  show(b)
  plugin.add(a)
  local second = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  show(c)
  local third = api.nvim_get_current_tabpage()
  vim.bo[b].modified = true
  vim.cmd("tabonly!")
  drain()
  equal(api.nvim_tabpage_is_valid(first), false)
  equal(api.nvim_tabpage_is_valid(second), false)
  equal(api.nvim_buf_is_valid(a), false)
  equal(plugin.buffers(third), { c, b })
  equal(#notices, 1)
end)

test("closing the final window of a tab triggers orphan cleanup", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  show(b)
  api.nvim_set_current_tabpage(first)
  vim.cmd("close")
  drain()
  equal(api.nvim_buf_is_valid(a), false)
  equal(plugin.buffers(), { b })
end)

test("orphan deletion failure recovers the buffer and is included in the close report", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  show(b)
  local second = api.nvim_get_current_tabpage()
  api.nvim_buf_delete = function(buf, opts)
    if buf == a then
      error("cannot delete orphan")
    end
    return saved.nvim_buf_delete(buf, opts)
  end
  local report = plugin.close_tab({ tab = first })
  equal(report.tab_closed, true)
  equal(report.closed, {})
  equal(#report.failed, 1)
  equal(plugin.owners(a), { second })
  equal(plugin.buffers(), { b, a })
  equal(#notices, 1)
end)

test("eligibility changes remove membership; background relisting does not adopt buffers", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  show(b)
  vim.bo[a].buftype = "nofile"
  plugin.refresh()
  equal(plugin.owners(a), {})
  vim.bo[a].buftype = ""
  drain()
  equal(plugin.owners(a), {})
  vim.bo[a].buflisted = false
  drain()
  vim.bo[a].buflisted = true
  drain()
  equal(plugin.owners(a), {})
  show(a)
  equal(plugin.buffers(), { b, a })
end)

test("bootstrap enrolls unloaded listed files without loading them", function()
  vim.cmd("badd /private/tmp/tab-buffers-tests/unloaded.lua")
  local buf = vim.fn.bufnr("/private/tmp/tab-buffers-tests/unloaded.lua")
  equal(api.nvim_buf_is_loaded(buf), false)
  plugin.setup()
  equal(plugin.buffers(), { buf })
  equal(api.nvim_buf_is_loaded(buf), false)
end)

test("native bdelete removes all memberships and queries return independent snapshots", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  show(b)
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  plugin.add(a)
  plugin.buffers(first)[1] = 9999
  plugin.owners(a)[1] = 9999
  plugin.tabs()[1] = 9999
  vim.cmd("bdelete " .. a)
  drain()
  equal(plugin.owners(a), {})
  equal(plugin.buffers(first), { b })
  equal(plugin.buffers(), {})
end)

test("navigation errors after changing a window restore the original buffer", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  show(b)
  local calls = 0
  api.nvim_win_set_buf = function(win, buf)
    calls = calls + 1
    saved.nvim_win_set_buf(win, buf)
    if calls == 1 then
      error("post-switch error")
    end
  end
  local selected, err = plugin.next()
  equal(selected, nil)
  assert(err:find("post-switch error", 1, true))
  equal(api.nvim_get_current_buf(), b)
  equal(plugin.buffers(), { a, b })
end)

test("reentrant adapter mutations from sort callbacks leave state intact", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  show(b)
  raises(function()
    plugin.sort(function()
      plugin.move(1)
      return false
    end)
  end, "already in progress")
  equal(plugin.buffers(), { a, b })
  equal(plugin.move_to(1), true)
end)

test("transfer failures preserve the source and never create destination membership", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  show(b)
  show(a)
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  local second = api.nvim_get_current_tabpage()
  api.nvim_set_current_tabpage(first)
  api.nvim_win_set_buf = function()
    error("transfer window error")
  end
  local moved, err = plugin.transfer(second)
  equal(moved, false)
  assert(err:find("transfer window error", 1, true))
  equal(plugin.buffers(first), { a, b })
  equal(plugin.buffers(second), {})
  equal(api.nvim_get_current_buf(), a)
end)

test("transfer rechecks a destination closed by third-party window callbacks", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  show(b)
  show(a)
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  local second = api.nvim_get_current_tabpage()
  api.nvim_set_current_tabpage(first)
  local once = false
  api.nvim_win_set_buf = function(win, buf)
    saved.nvim_win_set_buf(win, buf)
    if not once then
      once = true
      vim.cmd("tabclose " .. api.nvim_tabpage_get_number(second))
    end
  end
  local moved, err = plugin.transfer(second)
  equal(moved, false)
  assert(err:find("target tab closed", 1, true))
  equal(plugin.buffers(first), { a, b })
  equal(api.nvim_get_current_buf(), a)
end)

test("transfer no-ops and stale closing handles do not change state", function()
  plugin.setup()
  local a = file()
  show(a)
  local tab = api.nvim_get_current_tabpage()
  equal(plugin.transfer(tab), false)
  equal({ plugin.transfer(999999) }, { false, "invalid target tab handle" })
  local report = plugin.close({ buf = 999999 })
  equal(report.error, "invalid buffer handle")
  equal(plugin.close_tab({ tab = 999999 }).error, "invalid tab handle")
  raises(function()
    plugin.transfer(0)
  end)
  raises(function()
    plugin.close({ force = 1 })
  end)
  equal(plugin.buffers(), { a })
end)

test("last-tab bulk close preserves all regular splits and excludes special buffers", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  show(b)
  vim.cmd("vsplit")
  local tree_win = api.nvim_get_current_win()
  local tree = api.nvim_create_buf(true, false)
  vim.bo[tree].buftype = "nofile"
  api.nvim_win_set_buf(tree_win, tree)
  plugin.refresh()
  local windows = api.nvim_list_wins()
  local report = plugin.close_all({ tab = api.nvim_get_current_tabpage() })
  equal(report.closed, { a, b })
  equal(api.nvim_list_wins(), windows)
  equal(api.nvim_win_get_buf(tree_win), tree)
  local regular = windows[1] == tree_win and windows[2] or windows[1]
  equal(api.nvim_buf_get_name(api.nvim_win_get_buf(regular)), "")
  equal(api.nvim_get_current_win(), tree_win)
end)

test("an explicit last-tab close from the only special window adds an empty working split", function()
  plugin.setup()
  local a = file()
  show(a)
  local tree = api.nvim_create_buf(true, false)
  vim.bo[tree].buftype = "nofile"
  show(tree)
  local focus = api.nvim_get_current_win()
  plugin.close_all({ tab = api.nvim_get_current_tabpage() })
  equal(api.nvim_get_current_win(), focus)
  equal(api.nvim_win_get_buf(focus), tree)
  equal(#api.nvim_list_wins(), 2)
  equal(plugin.buffers(), {})
end)

test("empty selections retain empty tabs", function()
  plugin.setup()
  vim.cmd("tabnew")
  drain()
  equal(plugin.close_all(), { closed = {}, failed = {}, tab_closed = false })
  equal(#api.nvim_list_tabpages(), 2)
end)

test("last-window external close preserves modified wipe buffers", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  show(b)
  api.nvim_set_current_tabpage(first)
  vim.bo[a].modified, vim.bo[a].bufhidden = true, "wipe"
  api.nvim_win_close(api.nvim_get_current_win(), true)
  drain()
  equal(api.nvim_buf_is_valid(a), true)
  equal(vim.bo[a].modified, true)
  equal(vim.bo[a].bufhidden, "wipe")
  equal(plugin.buffers(), { b, a })
end)

test("tabonly preserves a modified wipe buffer shared only by closing tabs", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  vim.cmd("tab split")
  drain()
  vim.cmd("tabnew")
  show(b)
  vim.bo[a].modified, vim.bo[a].bufhidden = true, "wipe"
  vim.cmd("tabonly!")
  drain()
  equal(api.nvim_buf_is_valid(a), true)
  equal(vim.bo[a].bufhidden, "wipe")
  equal(plugin.buffers(), { b, a })
  equal(#notices, 1)
end)

test("teardown restores pending external closure protections and new setup recovers text", function()
  plugin.setup()
  local a = file()
  show(a)
  vim.cmd("tabnew")
  local second = api.nvim_get_current_tabpage()
  vim.bo[a].modified, vim.bo[a].bufhidden = true, "wipe"
  vim.cmd("tabclose 1")
  plugin.teardown()
  equal(vim.bo[a].bufhidden, "wipe")
  drain()
  plugin.setup()
  equal(plugin.owners(a), { second })
  equal(vim.bo[a].modified, true)
end)

for _, mode in ipairs({ "", "unload", "delete", "wipe" }) do
  test("shared close protects bufhidden=" .. (mode == "" and "default" or mode), function()
    plugin.setup()
    local a, b = file(), file()
    show(a)
    show(b)
    show(a)
    local first = api.nvim_get_current_tabpage()
    vim.cmd("tabnew")
    plugin.add(a)
    api.nvim_set_current_tabpage(first)
    vim.bo[a].modified, vim.bo[a].bufhidden = true, mode
    vim.o.hidden = false
    equal(plugin.close().closed, { a })
    equal(api.nvim_buf_is_loaded(a), true)
    equal(vim.bo[a].modified, true)
    equal(vim.bo[a].bufhidden, mode)
    equal(vim.bo[a].buflisted, true)
  end)
end

for _, method in ipairs({ "plugin", "native" }) do
  test(method .. " tab closure preserves excluded terminal jobs", function()
    plugin.setup()
    local a, b = file(), file()
    show(a)
    local first = api.nvim_get_current_tabpage()
    vim.cmd("enew")
    local terminal = api.nvim_get_current_buf()
    local job = vim.fn.jobstart({ "/bin/cat" }, { term = true })
    assert(job > 0, "could not start test terminal")
    vim.bo[terminal].bufhidden = "wipe"
    vim.cmd("tabnew")
    show(b)
    if method == "plugin" then
      plugin.close_tab({ tab = first })
    else
      vim.cmd("tabclose " .. api.nvim_tabpage_get_number(first))
    end
    drain()
    equal(api.nvim_buf_is_valid(terminal), true)
    equal(vim.fn.jobwait({ job }, 0)[1], -1)
    equal(vim.bo[terminal].bufhidden, "wipe")
    equal(plugin.owners(terminal), {})
    equal(api.nvim_buf_is_valid(a), false)
    vim.fn.jobstop(job)
  end)
end

test("VimLeavePre cancels queued reconciliation and orphan deletion", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  show(b)
  api.nvim_exec_autocmds("VimLeavePre", {})
  vim.cmd("tabclose " .. api.nvim_tabpage_get_number(first))
  drain()
  equal(api.nvim_buf_is_valid(a), true)
  equal(plugin.buffers(first), { a })
  equal(#notices, 0)
end)

test("errors after a committed deletion report the real outcome and close an emptied tab", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  show(b)
  api.nvim_buf_delete = function(buf, opts)
    saved.nvim_buf_delete(buf, opts)
    if buf == a then
      error("post-delete error")
    end
  end
  local report = plugin.close({ tab = first, buf = a })
  equal(report.closed, { a })
  equal(report.failed, {})
  equal(report.tab_closed, true)
  assert(report.error:find("post-delete error", 1, true))
  equal(plugin.buffers(), { b })
  equal(api.nvim_tabpage_is_valid(first), false)
end)

test("TabClosedPre errors still reconcile a tab that Neovim has closed", function()
  plugin.setup()
  local a, b = file(), file()
  show(a)
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  show(b)
  api.nvim_create_autocmd("TabClosedPre", {
    group = "TabBuffersTests",
    callback = function()
      error("closing callback error")
    end,
  })
  local report = plugin.close_tab({ tab = first })
  equal(report.tab_closed, true)
  equal(report.closed, { a })
  assert(report.error:find("closing callback error", 1, true))
  equal(api.nvim_buf_is_valid(a), false)
  equal(plugin.buffers(), { b })
end)

test("external closure captures a draft edited before deferred enrollment", function()
  plugin.setup()
  local first = api.nvim_get_current_tabpage()
  local draft = api.nvim_get_current_buf()
  vim.cmd("tabnew")
  drain()
  local second = api.nvim_get_current_tabpage()
  api.nvim_buf_set_lines(draft, 0, -1, false, { "unsaved draft" })
  api.nvim_set_current_tabpage(first)
  vim.cmd("tabclose!")
  drain()
  equal(api.nvim_buf_is_valid(draft), true)
  equal(api.nvim_buf_get_lines(draft, 0, -1, false), { "unsaved draft" })
  equal(plugin.owners(draft), { second })
  equal(#notices, 1)
end)

test("a tab created and closed within one callback still recovers unsaved text", function()
  plugin.setup()
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  local draft = api.nvim_get_current_buf()
  api.nvim_buf_set_lines(draft, 0, -1, false, { "new tab draft" })
  vim.bo[draft].bufhidden = "wipe"
  vim.cmd("tabclose!")
  drain()
  equal(plugin.owners(draft), { first })
  equal(vim.bo[draft].modified, true)
  equal(vim.bo[draft].bufhidden, "wipe")
  equal(#notices, 1)
end)

test("open preserves modified buffers with destructive bufhidden and focuses the target window", function()
  local a, b = file(), file()
  show(a)
  plugin.setup()
  plugin.add(b)
  vim.bo[a].modified, vim.bo[a].bufhidden = true, "wipe"
  equal(plugin.open(b), b)
  equal(api.nvim_get_current_buf(), b)
  equal(api.nvim_buf_is_valid(a), true)
  equal(vim.bo[a].bufhidden, "wipe")
  equal(plugin.buffers(), { a, b })
end)

test("open from a floating window uses a working window and preserves the float", function()
  local a, b = file(), file()
  show(a)
  local win = api.nvim_get_current_win()
  plugin.setup()
  plugin.add(b)
  local float = api.nvim_open_win(api.nvim_create_buf(false, true), true, {
    relative = "editor",
    width = 10,
    height = 2,
    row = 1,
    col = 1,
  })
  equal(plugin.open(b), b)
  equal(api.nvim_get_current_win(), win)
  equal(api.nvim_win_is_valid(float), true)
end)

test("open preserves a special-only tab by adding a working split", function()
  local b = file()
  plugin.setup()
  plugin.add(b)
  local tree = api.nvim_create_buf(false, true)
  local win = api.nvim_get_current_win()
  api.nvim_win_set_buf(win, tree)
  equal(plugin.open(b), b)
  equal(api.nvim_win_get_buf(win), tree)
  equal(#api.nvim_tabpage_list_wins(0), 2)
  equal(api.nvim_get_current_buf(), b)
end)

for _, direction in ipairs({ "horizontal", "vertical" }) do
  test("open creates a " .. direction .. " split without replacing the source", function()
    local a, b = file(), file()
    show(a)
    local source = api.nvim_get_current_win()
    plugin.setup()
    plugin.add(b)
    equal(plugin.open(b, { split = direction }), b)
    equal(api.nvim_win_get_buf(source), a)
    equal(api.nvim_get_current_buf(), b)
    equal(#api.nvim_tabpage_list_wins(0), 2)
    local first, second = api.nvim_win_get_position(source), api.nvim_win_get_position(api.nvim_get_current_win())
    equal(direction == "horizontal" and second[1] > first[1] or second[2] > first[2], true)
  end)
end

test("open rejects non-members, invalid handles and explicit special windows", function()
  local a = file()
  show(a)
  plugin.setup()
  local foreign = file()
  equal(select(1, plugin.open(foreign)), nil)
  equal(api.nvim_get_current_buf(), a)
  equal(plugin.owners(foreign), {})
  local dead = api.nvim_create_buf(true, false)
  api.nvim_buf_delete(dead, { force = true })
  equal(select(1, plugin.open(dead)), nil)
  local tree = api.nvim_create_buf(false, true)
  api.nvim_set_current_buf(tree)
  local win = api.nvim_get_current_win()
  equal(select(1, plugin.open(a, { win = win })), nil)
  equal(api.nvim_win_get_buf(win), tree)
  raises(function()
    plugin.open(a, { split = "diagonal" })
  end, "split")
end)

test("open can target another tab and restores the original window on failure", function()
  local a, b = file(), file()
  show(a)
  local first = api.nvim_get_current_tabpage()
  plugin.setup()
  vim.cmd("tabnew")
  show(b)
  local second, win = api.nvim_get_current_tabpage(), api.nvim_get_current_win()
  api.nvim_set_current_tabpage(first)
  equal(plugin.open(b, { tab = second }), b)
  equal(api.nvim_get_current_win(), win)
  plugin.add(a)
  local original = api.nvim_win_get_buf(win)
  api.nvim_win_set_buf = function(target, buf)
    saved.nvim_win_set_buf(target, buf)
    if buf == a then
      error("injected open failure")
    end
  end
  local opened, err = plugin.open(a)
  equal(opened, nil)
  assert(err:find("injected open failure", 1, true))
  equal(api.nvim_win_get_buf(win), original)
end)

test("open reports split creation errors without losing windows or focus", function()
  local a, b = file(), file()
  show(a)
  plugin.setup()
  local win = api.nvim_get_current_win()
  api.nvim_open_win = function()
    error("injected split failure")
  end
  local opened, err = plugin.open(b, { split = "vertical" })
  equal(opened, nil)
  assert(err:find("injected split failure", 1, true))
  equal(api.nvim_get_current_win(), win)
  equal(api.nvim_win_get_buf(win), a)
  equal(#api.nvim_tabpage_list_wins(0), 1)
end)

test("close_many deduplicates and uses model order with one report for partial failure", function()
  local a, b, c, foreign = file(), file(), file(), file()
  show(a)
  plugin.setup()
  plugin.add(b)
  plugin.add(c)
  -- foreign was bootstrapped as hidden: deliberately detach it by deleting.
  api.nvim_buf_delete(foreign, { force = true })
  vim.bo[b].modified = true
  local report = plugin.close_many({ c, b, a, c, foreign })
  equal(report.closed, { a, c })
  equal(#report.failed, 1)
  equal(report.failed[1].buf, b)
  equal(plugin.buffers(), { b })
  equal(api.nvim_get_current_buf(), b)
  equal(#notices, 1)
end)

test("close_many accepts an explicit list from a special window and preserves shared text", function()
  local a = file()
  show(a)
  plugin.setup()
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  show(a)
  local second = api.nvim_get_current_tabpage()
  api.nvim_set_current_tabpage(first)
  api.nvim_set_current_buf(api.nvim_create_buf(false, true))
  vim.bo[a].modified = true
  local report = plugin.close_many({ a })
  equal(report.closed, { a })
  equal(report.tab_closed, true)
  equal(plugin.owners(a), { second })
  equal(api.nvim_buf_is_valid(a), true)
  equal(vim.bo[a].modified, true)
end)

test("close_many empty or stale selections do not close tabs; invalid lists raise", function()
  plugin.setup()
  local tab = api.nvim_get_current_tabpage()
  equal(plugin.close_many({}).closed, {})
  equal(plugin.close_many({ 999999 }).closed, {})
  equal(api.nvim_tabpage_is_valid(tab), true)
  raises(function()
    plugin.close_many({ 0 })
  end, "positive")
  raises(function()
    plugin.close_many({ [2] = 1 })
  end, "dense")
  raises(function()
    plugin.close_many({ other = 1 })
  end, "integer")
end)

test("close_many force closes modified exclusive buffers and leaves an empty final tab", function()
  local a, b = file(), file()
  show(a)
  plugin.setup()
  plugin.add(b)
  vim.bo[a].modified, vim.bo[b].modified = true, true
  local report = plugin.close_many({ a, b }, { force = true })
  equal(report.closed, { a, b })
  equal(report.failed, {})
  equal(report.tab_closed, false)
  equal(plugin.buffers(), {})
  equal(api.nvim_buf_get_name(0), "")
end)

test("excluded tabs drop membership without deletion and all management functions leave their layout alone", function()
  local a, b = file(), file()
  show(a)
  plugin.setup()
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  show(b)
  local review, win = api.nvim_get_current_tabpage(), api.nvim_get_current_win()
  vim.t[review].tab_buffers_excluded = true
  api.nvim_exec_autocmds("User", { pattern = "TabBuffersContextChanged" })
  drain()
  equal(plugin.buffers(review), {})
  equal(plugin.owners(b), { first })
  equal(plugin.add(b, { tab = review }), false)
  equal(plugin.move(1, { tab = review, buf = b }), false)
  equal(plugin.next(), nil)
  equal(plugin.open(b, { tab = review }), nil)
  equal(plugin.close({ tab = review, buf = b }).closed, {})
  equal(plugin.close_many({ b }, { tab = review }).closed, {})
  equal(plugin.close_tab({ tab = review }).tab_closed, false)
  local changed, err = plugin.transfer(review, { tab = first, buf = a })
  equal(changed, false)
  assert(err:find("unmanaged", 1, true))
  equal(api.nvim_win_get_buf(win), b)
  equal(api.nvim_tabpage_is_valid(review), true)
  vim.cmd("tabclose")
  drain()
  equal(api.nvim_buf_is_valid(b), true)
end)

test("native closing an excluded tab before reconciliation never deletes its real files", function()
  plugin.setup()
  vim.cmd("tabnew")
  local a = file()
  api.nvim_set_current_buf(a)
  vim.t.tab_buffers_excluded = true
  vim.cmd("tabclose")
  drain()
  equal(api.nvim_buf_is_valid(a), true)
  equal(plugin.owners(a), {})
end)

test("external closure recovers unsaved files in a normal tab when only an excluded tab survives", function()
  local a = file()
  show(a)
  plugin.setup()
  local first = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  local review = api.nvim_get_current_tabpage()
  vim.t[review].tab_buffers_excluded = true
  plugin.refresh()
  api.nvim_set_current_tabpage(first)
  vim.bo[a].modified = true
  vim.cmd("tabclose!")
  drain()
  local destination = api.nvim_get_current_tabpage()
  assert(destination ~= review)
  equal(api.nvim_tabpage_is_valid(review), true)
  equal(plugin.owners(a), { destination })
  equal(vim.bo[a].modified, true)
  equal(plugin.buffers(review), {})
end)

test("bootstrap from an excluded tab assigns hidden files to an ordinary tab", function()
  local hidden, visible, review_file = file(), file(), file()
  show(visible)
  local normal = api.nvim_get_current_tabpage()
  vim.cmd("tabnew")
  show(review_file)
  local review = api.nvim_get_current_tabpage()
  vim.t[review].tab_buffers_excluded = true
  plugin.setup()
  equal(plugin.buffers(normal), { visible, hidden })
  equal(plugin.buffers(review), {})
  equal(plugin.owners(review_file), {})
end)

test("native diff windows in ordinary tabs still participate in membership", function()
  local a, b = file(), file()
  show(a)
  plugin.setup()
  vim.wo.diff = true
  plugin.refresh()
  equal(plugin.buffers(), { a, b })
  equal(plugin.next(), b)
  vim.wo.diff = false
end)

local failed = 0
for _, entry in ipairs(tests) do
  local ok, err = xpcall(function()
    reset()
    entry.run()
  end, debug.traceback)
  if ok then
    print("ok - " .. entry.name)
  else
    failed = failed + 1
    io.stderr:write("FAIL - " .. entry.name .. "\n" .. err .. "\n")
  end
end
reset()
vim.notify = real_notify
print(string.format("%d tests, %d failures", #tests, failed))
if failed > 0 then
  vim.cmd("cquit 1")
end
